### ISSUE TITLE
Mat på variantdag

### ISSUE THREAD

**Issue by strombraaten** [varianter/bk#2]
- [x] Hvor mange variantdager er det i løpet av ett år? `Det er 10 variantdager på ett år, der en av dem er variantturen.`
- [x] For å estimere karbonutslipp på maten som spises da, hvor setter vi grensa? Tenker vi kun lunsjen, eller eventuelt snacks også?
- [x] Om vi ser på lunsjen, hva slags gjennomsnitt er det vi ser etter da? Skiller vi mellom vegetar og kjøttmåltider?

**Comment by oddsve** [comment]
Det er 10 variantdager på ett år, der en av dem er variantturen.  

Når det gjelder mat har jeg et spørsmål. Hva tar vi ansvaret for? Bør vi ta ansvar for? For folk spiser jo hver dag, er det i vårt regnskap nå vi betaler?

**Comment by strombraaten** [comment]
Bra spørsmål, @oddsve , tenker at det er naturlig å se på det selskapet betaler for. Ikke hva folk spiser på en daglig basis. Sånn sett går det tilbake til det vi har snakka om før, at selskapet kan legge til rette for å ta gode valg, men at valget fremdeles er opp til hver enkelt. 

Derimot den ene dagen i måneden, hvor Variant faktisk betaler for maten, da bør det inngå i det totale klimautslippet som vi kartlegger. Det er iallefall mitt syn på det, men jeg er såklart åpen for innspill.

**Comment by linnhelendyrhaug** [comment]
Litt samme kommentaren som på #6. Vanskelig å få noe klimaavtrykk på lunsjen fra leverandør. Spurte på Britannia og det de kunne si var at det aller meste var lokale råvarer. Men vi har jo snart etablert en tradisjon for at folk kan velge mellom vegetar og kjøtt, så om vi har et snitt, vil vi jo kunne se i slack/bestilling til leverandør hvor mange av hver vi har gjennom et år.

**Comment by strombraaten** [comment]
Hå! Nå er du god, @linnhelendyrhaug , linker til og med inn andre issues her, ser jeg? Imponerende saker.

Men ja, det er et godt poeng. Hva tenker du er enklest å samle inn egentlig? Leite seg gjennom Slack for å finne resultatet på mat-avstemminger, eller samle inn lunsjbestillinger som er sendt til lokalet? Antar at det er @oddsve som har stått for de fleste bestillingene?

Om vi kan estimere vårs fram til 80-90% nøyaktighet vil nok det være godt nok altså, så om det er andre måter å telle seg fram på er det bare å komme med forslag.

**Comment by strombraaten** [comment]
Lukker denne siden vi har valgt å fokusere på de 4 store arrangementene våres enn så lenge (nyttårskalas, sommerfest, varianttur, julebord).
