### ISSUE TITLE
Sommerfest

### ISSUE THREAD

**Issue by strombraaten** [varianter/bk#6]
**Oppgaver**
- [ ] Finne et snitt for en vegetarlunsj
- [ ] Finne et snitt for en lunsj med eksempelvis 150 gram biff

**Bakgrunn**
- Hva veit vi?
- Hva må vi måle?
- Hva veit vi ingenting om, men kan potensielt sett estimere?

Hvordan gjør vi det med maten?
- Skiller vi mellom antall kjøtt- og vegetarmåltider?

Er det andre faktorer som spiller inn? Trenger vel ikke tenke på reise på et sånt arrangement.

**Comment by linnhelendyrhaug** [comment]
Erfaringsmessig er det ikke mange (om noen?) restauranter/leverandører som kan si noe om klimaavtrykk per rett ved bestilling. Så kanskje man kan ta et snitt ut i fra tall man finner på en vegetarlunsj vs lunsj med eksempelvis 150 gram biff? Og så har vi nå snart 3 Variantdager hvor folk har valgt og kan ta et snitt på fordeling derfra?

**Comment by strombraaten** [comment]
Løses av #17 

I samarbeid med SosKom, som har oversikt over antall deltagere.
