### ISSUE TITLE
Reiser internt

### ISSUE THREAD

**Issue by strombraaten** [varianter/bk#9]
**Hva veit vi?**
Her kan vi hente ut informasjon fra reiseregninga sannsynligvis, men hvordan gjør vi det egentlig? Hvem kan vi inkludere da? Og hvordan vurderer vi egentlig antallet? Baserer vi det på tall fra 2021? Ja, det gjør vi vel?

- Hva må vi måle?
- Er det noe vi ikke veit som vi kanskje må estimere?

**Comment by linnhelendyrhaug** [comment]
Her skal jo alt bli lagt inn dash og "registrer klimaavtrykk", ser variantturen mangler for mange eller alle. Her må vi legge inn alt samtidig nå tenker jeg? Her har vi kvittering på flyturene.

**Comment by strombraaten** [comment]
Lukker denne nå siden hver ansatt nå kan registrere reiser fortløpende, takket være arbeidet Mats og VariantDash-gjengen  gjorde med å registrere klimaavtrykk ✅

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/72508979/181255064-986f212a-cc7b-49e7-869d-199b5c23ff3b.png">
